version: '3.3'
services:
   wordpress:
     depends_on:
       - db
     build: .
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: clevertap
       WORDPRESS_DB_PASSWORD: clevertap
       WORDPRESS_DB_NAME: clevertap
       volumes:
          - ./html:/var/www/html
